version: '3.9'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --daemonize yes --save 20 1 --loglevel warning
  server_express:
    build:
      context: ./server-express
    scale: 3
  nginx:
    restart: always
    build:
      context: ./nginx-reverseproxy
    ports:
      - "80:80"

networks:
  default:
    name: net